=== PaloAltoNetworks/tcpsession/data/output_schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "sip": {
      "type": "string"
    },
    "dip": {
      "type": "string"
    },
    "sport": {
      "type": "integer"
    },
    "dport": {
      "type": "integer"
    },
    "proto": {
      "type": "integer"
    },
    "tcp_payload_hex": {
      "type": "array",
      "items": [
        {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "integer"
            },
            {
              "type": "string"
            }
          ]
        }
      ]
    },
    "tcp_ordered_hex_payload_md5sum": {
      "type": "string"
    },
    "tcp_payload_ascii": {
      "type": "array",
      "items": [
        {
          "type": "array",
          "items": [
            {
              "type": "string"
            },
            {
              "type": "integer"
            },
            {
              "type": "string"
            }
          ]
        }
      ]
    },
    "tcp_ordered_payload_md5sum": {
      "type": "string"
    },
    "combined_src_payload": {
      "type": "string"
    },
    "combined_src_payload_md5sum": {
      "type": "string"
    },
    "combined_dst_payload": {
      "type": "string"
    },
    "combined_dst_payload_md5sum": {
      "type": "string"
    }
  },
  "required": [
    "sip",
    "dip",
    "sport",
    "dport",
    "proto",
    "tcp_payload_hex",
    "tcp_ordered_hex_payload_md5sum",
    "tcp_payload_ascii",
    "tcp_ordered_payload_md5sum",
    "combined_src_payload",
    "combined_src_payload_md5sum",
    "combined_dst_payload",
    "combined_dst_payload_md5sum"
  ]
}

=== PaloAltoNetworks/tcpsession/data/sample_output.json
{
 "sip": "100.1.2.100",
 "dip": "200.1.5.182",
 "sport": 22482,
 "dport": 6095,
 "proto": 6,
 "tcp_payload_hex": [
  [
   "100.1.2.100",
   1,
   ""
  ],
  [
   "200.1.5.182",
   3,
   ""
  ],
  [
   "100.1.2.100",
   4,
   ""
  ],
  [
   "100.1.2.100",
   5,
   "4a4e4237304e010000ffff00030a0027000000006f00720067002e006d006f007a0069006c006c0061002e006a006100760061007300630072006900700074002e0074006f006f006c0073002e007300680065006c006c002e004d00610069006e0a000400000000650078006500630b01010000000a000f00000000530079007300740065006d002e0053007400720069006e0067005b005d0a0013000000005b004c006a006100760061002e006c0061006e0067002e0053007400720069006e0067003b0b01010000000c000f00000000530079007300740065006d002e004f0062006a006500630074005b005d0b01020000000a000f00000000530079007300740065006d002e0053007400720069006e0067005b005d0a0002000000002d00650a001600000000720075006e0043006f006d006d0061006e0064002800275c7830302f5c783030625c783030695c7830306e5c7830302f5c783030705c783030775c78303064002700290000"
  ],
  [
   "100.1.2.100",
   8,
   ""
  ]
 ],
 "tcp_ordered_hex_payload_md5sum": "583e061d930cd2f1cfee1632a94a2042",
 "tcp_payload_ascii": [
  [
   "100.1.2.100",
   1,
   ""
  ],
  [
   "200.1.5.182",
   3,
   ""
  ],
  [
   "100.1.2.100",
   4,
   ""
  ],
  [
   "100.1.2.100",
   5,
   "JNB70N\u0001\u0000\u0000\\xff\\xff\u0000\u0003\n\u0000'\u0000\u0000\u0000\u0000o\u0000r\u0000g\u0000.\u0000m\u0000o\u0000z\u0000i\u0000l\u0000l\u0000a\u0000.\u0000j\u0000a\u0000v\u0000a\u0000s\u0000c\u0000r\u0000i\u0000p\u0000t\u0000.\u0000t\u0000o\u0000o\u0000l\u0000s\u0000.\u0000s\u0000h\u0000e\u0000l\u0000l\u0000.\u0000M\u0000a\u0000i\u0000n\n\u0000\u0004\u0000\u0000\u0000\u0000e\u0000x\u0000e\u0000c\u000b\u0001\u0001\u0000\u0000\u0000\n\u0000\u000f\u0000\u0000\u0000\u0000S\u0000y\u0000s\u0000t\u0000e\u0000m\u0000.\u0000S\u0000t\u0000r\u0000i\u0000n\u0000g\u0000[\u0000]\n\u0000\u0013\u0000\u0000\u0000\u0000[\u0000L\u0000j\u0000a\u0000v\u0000a\u0000.\u0000l\u0000a\u0000n\u0000g\u0000.\u0000S\u0000t\u0000r\u0000i\u0000n\u0000g\u0000;\u000b\u0001\u0001\u0000\u0000\u0000\f\u0000\u000f\u0000\u0000\u0000\u0000S\u0000y\u0000s\u0000t\u0000e\u0000m\u0000.\u0000O\u0000b\u0000j\u0000e\u0000c\u0000t\u0000[\u0000]\u000b\u0001\u0002\u0000\u0000\u0000\n\u0000\u000f\u0000\u0000\u0000\u0000S\u0000y\u0000s\u0000t\u0000e\u0000m\u0000.\u0000S\u0000t\u0000r\u0000i\u0000n\u0000g\u0000[\u0000]\n\u0000\u0002\u0000\u0000\u0000\u0000-\u0000e\n\u0000\u0016\u0000\u0000\u0000\u0000r\u0000u\u0000n\u0000C\u0000o\u0000m\u0000m\u0000a\u0000n\u0000d\u0000(\u0000'\\x00/\\x00b\\x00i\\x00n\\x00/\\x00p\\x00w\\x00d\u0000'\u0000)\u0000\u0000"
  ],
  [
   "100.1.2.100",
   8,
   ""
  ]
 ],
 "tcp_ordered_payload_md5sum": "f9144f0ca71c169539bfe5442b098247",
 "combined_src_payload": "JNB70N\u0001\u0000\u0000\\xff\\xff\u0000\u0003\n\u0000'\u0000\u0000\u0000\u0000o\u0000r\u0000g\u0000.\u0000m\u0000o\u0000z\u0000i\u0000l\u0000l\u0000a\u0000.\u0000j\u0000a\u0000v\u0000a\u0000s\u0000c\u0000r\u0000i\u0000p\u0000t\u0000.\u0000t\u0000o\u0000o\u0000l\u0000s\u0000.\u0000s\u0000h\u0000e\u0000l\u0000l\u0000.\u0000M\u0000a\u0000i\u0000n\n\u0000\u0004\u0000\u0000\u0000\u0000e\u0000x\u0000e\u0000c\u000b\u0001\u0001\u0000\u0000\u0000\n\u0000\u000f\u0000\u0000\u0000\u0000S\u0000y\u0000s\u0000t\u0000e\u0000m\u0000.\u0000S\u0000t\u0000r\u0000i\u0000n\u0000g\u0000[\u0000]\n\u0000\u0013\u0000\u0000\u0000\u0000[\u0000L\u0000j\u0000a\u0000v\u0000a\u0000.\u0000l\u0000a\u0000n\u0000g\u0000.\u0000S\u0000t\u0000r\u0000i\u0000n\u0000g\u0000;\u000b\u0001\u0001\u0000\u0000\u0000\f\u0000\u000f\u0000\u0000\u0000\u0000S\u0000y\u0000s\u0000t\u0000e\u0000m\u0000.\u0000O\u0000b\u0000j\u0000e\u0000c\u0000t\u0000[\u0000]\u000b\u0001\u0002\u0000\u0000\u0000\n\u0000\u000f\u0000\u0000\u0000\u0000S\u0000y\u0000s\u0000t\u0000e\u0000m\u0000.\u0000S\u0000t\u0000r\u0000i\u0000n\u0000g\u0000[\u0000]\n\u0000\u0002\u0000\u0000\u0000\u0000-\u0000e\n\u0000\u0016\u0000\u0000\u0000\u0000r\u0000u\u0000n\u0000C\u0000o\u0000m\u0000m\u0000a\u0000n\u0000d\u0000(\u0000'\\x00/\\x00b\\x00i\\x00n\\x00/\\x00p\\x00w\\x00d\u0000'\u0000)\u0000\u0000",
 "combined_src_payload_md5sum": "f9144f0ca71c169539bfe5442b098247",
 "combined_dst_payload": "",
 "combined_dst_payload_md5sum": "d41d8cd98f00b204e9800998ecf8427e"
}
